# Generated by Django 3.1.1 on 2020-11-26 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201124_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='rating_scale',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 11, 47, 27, 964329)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 11, 47, 27, 970360)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 11, 47, 27, 968360)),
        ),
    ]
