# Generated by Django 3.1.1 on 2020-11-26 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201126_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='stockk',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='fk', to='myapp.stock'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 12, 0, 22, 709882)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 12, 0, 22, 714871)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 12, 0, 22, 712915)),
        ),
    ]
