# Generated by Django 3.1.2 on 2020-10-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_stock_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='change_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
