# Generated by Django 3.1.2 on 2020-11-02 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20201103_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 1, 59, 2, 715041)),
        ),
    ]
