# Generated by Django 3.1.2 on 2020-11-09 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20201103_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 0, 13, 19, 623526)),
        ),
    ]
