# Generated by Django 3.1.2 on 2020-11-09 22:16

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0020_auto_20201110_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='portfolio',
            field=models.ManyToManyField(related_name='port_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 0, 16, 26, 42166)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='favorite',
            field=models.ManyToManyField(related_name='fav_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
