# Generated by Django 3.1.2 on 2020-11-10 00:40

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0022_auto_20201110_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='shares',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 2, 40, 8, 527921)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 2, 40, 8, 528918)),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='portfolio_list',
        ),
        migrations.AddField(
            model_name='stock',
            name='portfolio_list',
            field=models.ManyToManyField(related_name='port_set', through='myapp.Portfolio',
                                         to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AlterField(
        #     model_name='stock',
        #     name='portfolio_list',
        #     field=models.ManyToManyField(related_name='port_set', through='myapp.Portfolio', to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'stock')},
        ),
    ]
